Updates redis

diff --git a/.github/workflows/image-tests.yml b/.github/workflows/image-tests.yml
--- a/.github/workflows/image-tests.yml
+++ b/.github/workflows/image-tests.yml
@@ -48,10 +48,21 @@ jobs:
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache-new
 
+      - name: Find Redis network
+        id: redis_network
+        run: |
+          network_name=$(docker network ls --filter name=redis -q)
+          if [ -z "$network_name" ]; then
+            echo "Redis network not found"
+            exit 1
+          fi
+          echo "::set-output name=network_name::$network_name"
+
       - name: Run tests in Docker container
         run: |
           docker run --rm \
             -e BLOT_REDIS_HOST=redis \
+            --network ${{ steps.redis_network.outputs.network_name }} \
             my-node-app-builder npm test
 
       - name: Move cache
