Adds production health check

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -80,7 +80,7 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build amd64 production image
+      - name: Build production image 
         uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64,linux/arm64
@@ -89,6 +89,33 @@ jobs:
           cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/blot
           cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/blot,mode=max
           tags: ghcr.io/${{ github.repository_owner }}/blot:${{ github.sha }}-pending
+
+      - name: Verify built-in health check
+        env:
+          IMAGE: ghcr.io/${{ github.repository_owner }}/blot:${{ github.sha }}-pending
+        run: |
+          # Start a container in detached mode
+          container_id=$(docker run -d --rm $IMAGE)
+
+          echo "Waiting for the container to pass the built-in health check..."
+
+          # Wait for the container's health status to be "healthy"
+          timeout=60  # Maximum wait time in seconds
+          interval=5  # Interval between health status checks
+          elapsed=0
+          while [ "$(docker inspect --format='{{json .State.Health.Status}}' $container_id)" != '"healthy"' ]; do
+            if [ $elapsed -ge $timeout ]; then
+              echo "Health check failed: container did not become healthy within $timeout seconds."
+              docker logs $container_id
+              docker stop $container_id
+              exit 1
+            fi
+            sleep $interval
+            elapsed=$((elapsed + interval))
+          done
+
+          echo "Container passed the health check."
+          docker stop $container_id
 
   release:
     runs-on: ubuntu-latest
